Advanced Building Blocks - Bubble Sort
mricanho/Bubble-sort pull request #2
Opened 2020-11-25 20:43 UTC by mricanho

We created bubble_sort and bubble_sort_by methods.

We used the bubble sort algorithm and for that, we applied booleans and loops

2020-11-25 21:15 UTC, Spayco requested changes
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

- [ ] check below 👇 

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2020-11-25 21:15 UTC, Spayco commented on main.rb
> +# puts bubble_sort([3, 2, 1, 85, 1, 58, 6, 4])
- [ ] remove commented code ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

2020-11-25 21:15 UTC, Spayco commented on main.rb
> +puts compare
- [ ] No debugging instructions in committed code (as discussed [here](https://questions.microverse.org/t/debugging-instructions-code/346)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/section/debugging_requirement.png) from Pathwright)

2020-11-25 21:15 UTC, Spayco commented on main.rb
> +end
- [ ] #bubble_sort_by isn't working, if you try `bubble_sort_by(%w[hi hello hey]) { |left, right| left.length + right.length }` it wouldn't give the right result (`[hello hey hi]`) (Hint: you're not using `yield`)

2020-11-26 04:34 UTC, kitpao requested changes
# 👋 Hello @mricanho and @AhmedAmin90 

Good job making your methods pass all the tests we have. You followed the principle of bubble sort correctly. 👏 You have one technical detail, please check below 🔽 

**_Note:_** All the **[OPTIONAL]** are **not required** in order to approve your project but are personal suggestions to improve your coding experience

If you are curious about optimizing your code, you can take a look at the resulting code at the end of [this article](https://medium.com/swlh/bubble-sort-algorithm-how-to-develop-your-computational-thinking-c092a9b4bf16)

### ♻️ Status: Your project requires 1 additional change ♻️
➡️ Please request another review once you are ready 📝 
___
##### 👉 If you have any doubts you can contact me on slack as @kitpao
##### 🌟  If you have feedback about my reviews I would appreciate it if you could leave a recommendation in LinkedIn 💌 or let me know in Slack if you see improvements to be done 😄  

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-11-26 04:34 UTC, kitpao commented on main.rb
> +  (0..number_ofloop).each do |_i|
- [ ] **OPTIONAL** It is a convention in Ruby to use the only `_` for unused parameters, or you could skip the parameters as well and leave it like: `(0..number_ofloop).each do`

2020-11-26 04:34 UTC, kitpao commented on main.rb
> +  (0..number_ofloop).each do |_i|
- [ ] **OPTIONAL** It is a convention in Ruby to use the only `_` for unused parameters, or you could skip the parameters as well and leave it like: `(0..number_ofloop).each do`

2020-11-26 04:34 UTC, kitpao commented on main.rb
> +puts bubble_sort([4, 3, 78, 2, 0, 2])
- [ ] Please delete this line of debugging code (in the future you will learn to make automated tests for these cases). For now, if you want, you could save your examples in a different file and gitignore it (you will find it useful for enumerables project)
![image](https://user-images.githubusercontent.com/53256139/100308221-707b4680-2f6d-11eb-8c84-fbd63f02f03b.png)

2020-11-26 05:22 UTC, kitpao approved these changes
# 👋 Hello @AhmedAmin90 and @mricanho 

Great job 💯 your project complies with all requirements 🥳 

### 👏 Your project has been approved 👏
### 🚀 You may merge to main and submit the project completition form 🚀

___
##### 👉 If you have any doubts you can contact me on slack as @kitpao
##### 🌟  If you have feedback about my reviews I would appreciate it if you could leave a recommendation in LinkedIn 💌 or let me know in Slack if you see improvements to be done 😄  

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-11-26 05:24 UTC, merged